direction: max
fold: 4
hpo_metric: eval_AP_weighted
learning_rate: 9.873122827827431e-05
loss_type: BCE
model_name: google-bert/bert-base-uncased
num_trials: 30
pos_weight_ias: 0.5837434717626788
pos_weight_sua: 3.1388484246005146
pos_weight_va: 2.445199140791167
run_idx: 0
weight_decay: 1.7299151461878281e-06
with_keywords: false
with_title: true
