direction: max
fold: 4
hpo_metric: eval_AP_weighted
learning_rate: 7.340675018434774e-05
loss_type: BCE
model_name: google-bert/bert-base-uncased
num_trials: 20
pos_weight: 3.9109029727093
run_idx: 0
weight_decay: 0.00011233621690895227
with_keywords: false
with_title: true
