direction: max
fold: 0
hpo_metric: eval_AP_weighted
learning_rate: 7.646967812163098e-05
loss_type: BCE
model_name: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract
num_trials: 20
pos_weight_ias: 1.556424963478957
pos_weight_sua: 3.5269805559162744
pos_weight_va: 3.236724085963455
run_idx: 0
weight_decay: 2.7586210854738336e-05
with_keywords: false
with_title: true
